language: node_js
node_js:
  - "4.4.4"
before_script:
  - cd dailymagiceye
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install -g mocha
  - npm install
